/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'btu' at '11/27/15 8:07 PM' with Gradle 2.5
 *
 * @author btu, @date 11/27/15 8:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
